// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGm0DCSzJF9D7veMGTTcO_XHvOZofD2IA',
    appId: '1:258402858871:web:d4c04d15534e563f5f5372',
    messagingSenderId: '258402858871',
    projectId: 'rana-2399b',
    authDomain: 'rana-2399b.firebaseapp.com',
    storageBucket: 'rana-2399b.firebasestorage.app',
    measurementId: 'G-TV083YKYHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5-BBC_wZVUltMPOeI7S_arPYAfFQtOUU',
    appId: '1:258402858871:android:d6eb128c4bb84a955f5372',
    messagingSenderId: '258402858871',
    projectId: 'rana-2399b',
    storageBucket: 'rana-2399b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-cXU_Of-xHguRhVptWNJoQyGhM3wKhM',
    appId: '1:258402858871:ios:6762f25d8775bffd5f5372',
    messagingSenderId: '258402858871',
    projectId: 'rana-2399b',
    storageBucket: 'rana-2399b.firebasestorage.app',
    iosBundleId: 'com.example.flutterLab5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-cXU_Of-xHguRhVptWNJoQyGhM3wKhM',
    appId: '1:258402858871:ios:6762f25d8775bffd5f5372',
    messagingSenderId: '258402858871',
    projectId: 'rana-2399b',
    storageBucket: 'rana-2399b.firebasestorage.app',
    iosBundleId: 'com.example.flutterLab5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGm0DCSzJF9D7veMGTTcO_XHvOZofD2IA',
    appId: '1:258402858871:web:ee4863e85ca9fdbf5f5372',
    messagingSenderId: '258402858871',
    projectId: 'rana-2399b',
    authDomain: 'rana-2399b.firebaseapp.com',
    storageBucket: 'rana-2399b.firebasestorage.app',
    measurementId: 'G-8DY836YR8H',
  );
}
